//! # Gateway Upload Response Types
//!
//! This module defines the response structures returned by the gateway
//! after a successful or failed upload operation.
//!
//! These types are typically deserialized from JSON responses produced
//! by DeOSS-compatible gateway services and are shared across multiple
//! upload APIs (standard, streaming, resumable).
//!
//! A successful upload response usually contains a file identifier (`fid`)
//! that can later be used to download or reference the uploaded object.

use serde::Deserialize;

/// Upload response payload data.
///
/// Contains the unique file identifier generated by the gateway
/// for the uploaded object.
#[derive(Deserialize, Debug)]
pub struct Data {
    pub fid: String,
}

/// Gateway upload response.
///
/// This structure represents the top-level JSON response returned
/// by the gateway for upload-related requests.
#[derive(Deserialize, Debug)]
pub struct UploadResponse {
    pub code: i32,
    pub msg: String,
    pub data: Option<Data>,
}
